# In-class exercise 9: Deep Learning (Part 1A)
In this notebook we will see how to write efficient and numerically stable code.

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time

%matplotlib inline

from sklearn.datasets import load_breast_cancer
from sklearn.metrics import accuracy_score, f1_score
from sklearn.preprocessing import minmax_scale

In [2]:
X, y = load_breast_cancer(return_X_y=True)

# Scale each feature to [-1, 1] range
X = minmax_scale(X, feature_range=(-1, 1))

# 1. Vectorization

## 1.1. Logistic regression (two classes)

**Setting:** Logistic regression (two classes)

**Task:** Generate predictions for the entire dataset

In [3]:
n_features = X.shape[1]
w = np.random.normal(size=[n_features], scale=0.1)  # weight vector
b = np.random.normal(size=[1])  # bias

In [4]:
def sigmoid(t):
    """Apply sigmoid to the input array."""
    return 1 / (1 + np.exp(-t))

### Bad - for loops

In [5]:
def predict_for_loop(X, w, b):
    """Generate predictions with a logistic regression model using a for-loop.
    
    Args:
        X: data matrix, shape (N, D)
        w: weights vector, shape (D)
        b: bias term, shape (1)
        
    Returns:
        y: probabilies of the positive class, shape (N)
    """
    n_samples = X.shape[0]
    y = np.zeros([n_samples])
    for i in range(n_samples):
        score = np.dot(X[i], w) + b
        y[i] = sigmoid(score)
    return y

### Good - vectorization

In [6]:
def predict_vectorized(X, w, b):
    """Generate predictions with a logistic regression model using vectorized operations.
    
    Args:
        X: data matrix, shape (N, D)
        w: weights vector, shape (D)
        b: bias term, shape (1)
        
    Returns:
        y: probabilies of the positive class, shape (N)
    """
    scores = X @ w + b
    y = sigmoid(scores)
    return y

### Compare the runtime of two variants

In [7]:
%%timeit
predict_for_loop(X, w, b)

4.48 ms ± 214 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
%%timeit
predict_vectorized(X, w, b)

63.5 µs ± 7.12 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


## 1.2. K-nearest neighbors
A more complicated task: compute the matrix of pairwise distances.

Given a data matrix `X` of size `[N, D]`, compute the matrix `dist` of pairwise distances of size `[N, N]`, where `dist[i, j] = l2_distance(X[i], X[j])`.

### Bad - for loops

In [9]:
def l2_distance(x, y):
    """Compute Euclidean distance between two vectors."""
    return np.sqrt(np.sum((x - y) ** 2))
# x and y have the same size

In [10]:
def distances_for_loop(X):
    """Compute pairwise distances between all instances (for loop version).
    
    Args:
        X: data matrix, shape (N, D)
        
    Returns:
        dist: matrix of pairwise distances, shape (N, N)
    """
    n_samples = X.shape[0]
    distances = np.zeros([n_samples, n_samples])
    for i in range(n_samples):
        for j in range(n_samples):
            distances[i, j] = l2_distance(X[i], X[j])
    return distances

In [11]:
dist1 = distances_for_loop(X)

### Good - vectorization

How can we compute all the distances in a vectorized way?

Start with a simpler example.

In [12]:
x = np.arange(5, dtype=np.float64)

Increase the dimension of an array using `np.newaxis`

In [13]:
x[:, np.newaxis]
# Transpose here

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.]])

In [14]:
x[np.newaxis, :] - x[:, np.newaxis]
# perform the vector in extention
#computer the distance among each pair of points without using new variables
#we can also substitude newaxis here with None, the result is the same

array([[ 0.,  1.,  2.,  3.,  4.],
       [-1.,  0.,  1.,  2.,  3.],
       [-2., -1.,  0.,  1.,  2.],
       [-3., -2., -1.,  0.,  1.],
       [-4., -3., -2., -1.,  0.]])

In [15]:
def distances_vectorized(X):
    """Compute pairwise distances between all instances (vectorized version).
    
    Args:
        X: data matrix, shape (N, D)
        
    Returns:
        dist: matrix of pairwise distances, shape (N, N)
    """
    return np.sqrt(((X[:, None] - X[None, :])**2).sum(-1))

In [16]:
dist2 = distances_vectorized(X)

Make sure that both variants produce the same results

In [17]:
# Direct comparison fails because of tiny numerical differences
np.all(dist1 == dist2)

True

In [18]:
# Two results are very close
np.linalg.norm(dist1 - dist2, ord='fro')

0.0

In [19]:
# Use np.allclose to compare
np.allclose(dist1, dist2)

True

### Best - library function

In [20]:
from scipy.spatial.distance import cdist, pdist, squareform

dist3 = cdist(X, X)
dist4 = squareform(pdist(X))

### Compare the runtime

In [21]:
%%timeit
dist1 = distances_for_loop(X)

2.27 s ± 136 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [22]:
%%timeit
dist2 = distances_vectorized(X)

88.4 ms ± 13.8 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [23]:
3280 / 65.5
# a significant difference here

50.0763358778626

In [24]:
%%timeit
dist3 = cdist(X, X)

8.38 ms ± 858 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [25]:
%%timeit
dist4 = squareform(pdist(X))

4.78 ms ± 57.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


## Lessons:
1. For-loops are extremely slow! Avoid them whenever possible.
2. A better alternative - use matrix operations & broadcasting
3. An even better alternative - use library functions (if they are available).
4. Implementations with for-loops can be useful for debugging vectorized code.

# 2. Numerical stability
Typically, GPUs use single precision (32bit) floating point numbers (in some cases even half precision / 16bit). This significantly speeds ups the computations, but also makes numerical issues a lot more likely. 
Because of this we always have to be extremely careful to implement our code in a numerically stable way.

Most commonly, numerical issues occur when dealing with `log` and `exp` functions (e.g. when computing cross-entropy of a categorical distribution) and `sqrt` for values close to zero (e.g. when computing standard deviations or normalizing the $L_2$ norm).

## 2.1. Avoiding numerical overflow (exploding `exp`)

Softmax function $f : \mathbb{R}^D \to \Delta^{D - 1}$ converts a vector $\mathbf{x} \in \mathbb{R}^D$ into a vector of probabilities.

$$f(\mathbf{x})_j = \frac{\exp(x_j)}{\sum_{d=1}^{D} \exp(x_d)}$$

Apply the softmax function to the following vector.

In [26]:
# double type is very useful since it satisfies almost all common used (float 64)


In [27]:
x = np.linspace(0., 4., 5).astype(np.float32)
x

array([0., 1., 2., 3., 4.], dtype=float32)

In [28]:
# Our code here
denominator = np.exp(x).sum()
np.exp(x) / denominator

array([0.01165623, 0.03168492, 0.08612855, 0.23412167, 0.6364086 ],
      dtype=float32)

Now apply it to the following vector

In [29]:
x = np.linspace(50., 90., 5).astype(np.float32)
x

array([50., 60., 70., 80., 90.], dtype=float32)

In [30]:
np.exp(x)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


array([5.1847055e+21, 1.1420074e+26, 2.5154387e+30, 5.5406225e+34,
                 inf], dtype=float32)

In [31]:
# Our code here
denominator = np.exp(x).sum()
np.exp(x) / denominator

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: overflow encountered in exp
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: RuntimeWarning: invalid value encountered in true_divide
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0.,  0.,  0.,  0., nan], dtype=float32)

How to avoid the exposion?

In [32]:
x_shifted = x - np.max(x)
denominator = np.exp(x_shifted).sum()
np.exp(x_shifted) / denominator

array([4.248161e-18, 9.357198e-14, 2.061060e-09, 4.539787e-05,
       9.999546e-01], dtype=float32)

In [33]:
np.exp(x_shifted).sum(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

## 2.2. Working in the log-space / simplifying the expressions

Binary cross entropy (BCE) loss for a logistic regression model (corresponds to negative log-likelihood of a Bernoulli model)

$$\log p(\mathbf{y} \mid \mathbf{X}, \mathbf{w}, b) = -\sum_{i=1}^{N} y_i \log \sigma(\mathbf{w}^T \mathbf{x}_i + b) + (1 - y_i) \log (1 - \sigma(\mathbf{w}^T \mathbf{x}_i + b))$$


Implement the BCE computation.

In [ ]:
# TODO
def sigmoid(t):
    return 1 / (1 + np.exp(-t))

def binary_cross_entropy_unstable(scores, labels):
    return -labels * np.log(sigmoid(scores)) - (1 - labels) * np.log(1 - sigmoid(scores))

In [ ]:
x = np.array([[20., 20.]])
w = np.array([[1., 1.]])
y = np.array([1.])

scores = x @ w.T
binary_cross_entropy_unstable(scores, y)

Try to simplify the BCE loss as much as possible

In [ ]:
# TODO
def binary_cross_entropy_stable(scores, labels):
    return np.log(1 + np.exp(scores)) - labels * scores

binary_cross_entropy_stable(scores, y)

## 2.3. Loss of numerical precision

Implement the log sigmoid function 

$$f(x) = \log \sigma(x) = \log \left(\frac{1}{1 + \exp(-x)}\right)$$

In [ ]:
# Your code here
def log_sigmoid_unstable(x):
    return np.log(1 / (1 + np.exp(-x)))

`float32` has much lower "resolution" than `float64`

In [ ]:
x = np.linspace(0, 30, 11).astype(np.float32)
log_sigmoid_unstable(x)

In [ ]:
x = np.linspace(0, 30, 11).astype(np.float64)
log_sigmoid_unstable(x)

Implement the log-sigmoid function in a numerically stable way

In [ ]:
def log_sigmoid_stable(x):
    return -np.log1p(np.exp(-x))

In [ ]:
x = np.linspace(0, 30, 11).astype(np.float32)
log_sigmoid_stable(x)

Relevant functions: `np.log1p`, `np.expm1`, `scipy.special.logsumexp`, `scipy.special.softmax` -- these are also implemented in all major deep learning frameworks.

## Lessons:
1. Be especially careful when working with `log` and `exp` functions in **single precision** floating point arithmetics
2. Work in the log-space when possible
3. Use numerically stable library functions when available